os:
  - osx
script:
  - uname
  - brew install kafka
  - ls /usr/local/Cellar/kafka
  - ls /usr/local/bin
  - ls /usr/local/etc/kafka
  - ls /usr/local/etc/zookeeper
  - ls /usr/local/var/lib/kafka-logs
